schema_version = 1
doc_type = "fitrep"
name = "JONES, JOHN P"
rate = "LTJG"
desig = "1110"
ssn = "000-00-0000"
group = "ACT"
uic = "12345"
station = "NAVPERSCOM"
promotion_status = "REGULAR"
date_reported = 2022-09-22
period_start = 2024-05-27
period_end = 2025-02-28
not_observed = false
regular = true
physical_readiness = "P"
billet_subcategory = "NA"
senior_name = "HOPPER, G"
senior_grade = "CAPT"
senior_desig = "1840"
senior_title = "CO"
senior_uic = "12345"
senior_ssn = "000-00-0000"
job = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id mattis elit. Aliquam et sem bibendum, laoreet risus eget, malesuada nisl. Praesent gravida leo cursus velit mattis eleifend. Sed interdum lacinia efficitur. Sed elementum gravida at."
duties_abbreviation = "EXAMPLE"
duties_description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id mattis elit. Aliquam et sem bibendum, laoreet risus eget, malesuada nisl. Praesent gravida leo cursus velit mattis eleifend."
date_counseled = 2024-08-14
counselor = "NIMITZ, C"
trait1 = 1
trait2 = 2
trait3 = 3
trait4 = 4
trait5 = 5
trait6 = 5
trait7 = 5
career_rec_1 = "Lorem ipsum egestas"
career_rec_2 = "Lorem ipsum egestas"
comments = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus enim quis magna vestibulum sagittis. Aenean ut pretium libero. Quisque maximus risus vitae ligula mollis viverra. Nullam auctor justo diam, eu porta tellus egestas sit amet. Vivamus et elit non mi imperdiet sodales nec id tellus. Cras sodales scelerisque massa, vel pulvinar erat. Donec molestie augue diam, sed consequat sem vulputate vel. Mauris luctus mi eu tellus tempus, non scelerisque libero imperdiet. Integer facilisis velit ac ligula scelerisque, eu dignissim magna cursus. Vivamus nec libero eget urna congue egestas et id est. Nunc tincidunt lorem erat, ut aliquam magna vulputate eu.  Sed dapibus, augue eget blandit accumsan, velit diam consequat enim, eget rhoncus lorem erat in neque. Nam lobortis volutpat congue. Morbi urna nisl, tincidunt non metus sed, ornare bibendum lectus. Etiam consequat malesuada ligula, eu luctus felis ullamcorper a. Praesent massa massa, cursus non mauris in, finibus porta metus. Integer gravida et risus ac scelerisque. Mauris ut tellus efficitur nunc gravida pharetra. Phasellus vitae nisi vitae tellus mollis consequat tincidunt semper risus. Vivamus nec nulla vitae nunc tristique ornare.  Nulla facilisi. Phasellus nisl sem, imperdiet eget hendrerit elementum, semper quis justo. Mauris at purus hendrerit, molestie orci ut, maximus est. Praesent congue tincidunt sapien, vitae egestas neque auctor sed. Curabitur feugiat orci lorem, a fringilla leo fringilla malesuada. Praesent mattis ornare magna, id consectetur massa. Etiam consectetur lorem eu pellentesque sollicitudin. Proin dapibus leo eu justo."
indiv_promo_rec = 3
senior_address = "123 Main St, Anytown, USA"
periodic = false
det_indiv = false
special = false
concurrent = false
det_rs = false
ops_cdr = false
