from datetime import date

from navfitx.models import (
    BilletSubcategory,
    ChiefEval,
    DutyStatus,
    Eval,
    Fitrep,
    PromotionStatus,
    RetentionRecommendation,
)


def build_validated_example_fitrep() -> Fitrep:
    return Fitrep(
        id=1,
        name="JONES, JOHN P",
        rate="LTJG",
        desig="1110",
        ssn="000-00-0000",
        group=DutyStatus.ACT,
        uic="12345",
        station="NAVPERSCOM",
        promotion_status=PromotionStatus.REGULAR,
        date_reported=date(2022, 9, 22),
        period_start=date(2024, 5, 27),
        period_end=date(2025, 2, 28),
        not_observed=False,
        regular=True,
        physical_readiness="P",
        billet_subcategory=BilletSubcategory.NA,
        senior_name="HOPPER, G",
        senior_grade="CAPT",
        senior_desig="1840",
        senior_title="CO",
        senior_uic="12345",
        senior_ssn="000-00-0000",
        job="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id mattis elit. Aliquam et sem bibendum, laoreet risus eget, malesuada nisl. Praesent gravida leo cursus velit mattis eleifend. Sed interdum lacinia efficitur. Sed elementum gravida at.",
        duties_abbreviation="EXAMPLE",
        duties_description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id mattis elit. Aliquam et sem bibendum, laoreet risus eget, malesuada nisl. Praesent gravida leo cursus velit mattis eleifend.",
        date_counseled=date(2024, 8, 14),
        counselor="NIMITZ, C",
        career_rec_1="Lorem ipsum egestas",
        career_rec_2="Lorem ipsum egestas",
        trait1=1,
        trait2=2,
        trait3=3,
        trait4=4,
        trait5=5,
        trait6=5,
        trait7=5,
        comments="Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus enim quis magna vestibulum sagittis. Aenean ut pretium libero. Quisque maximus risus vitae ligula mollis viverra. Nullam auctor justo diam, eu porta tellus egestas sit amet. Vivamus et elit non mi imperdiet sodales nec id tellus. Cras sodales scelerisque massa, vel pulvinar erat. Donec molestie augue diam, sed consequat sem vulputate vel. Mauris luctus mi eu tellus tempus, non scelerisque libero imperdiet. Integer facilisis velit ac ligula scelerisque, eu dignissim magna cursus. Vivamus nec libero eget urna congue egestas et id est. Nunc tincidunt lorem erat, ut aliquam magna vulputate eu.  Sed dapibus, augue eget blandit accumsan, velit diam consequat enim, eget rhoncus lorem erat in neque. Nam lobortis volutpat congue. Morbi urna nisl, tincidunt non metus sed, ornare bibendum lectus. Etiam consequat malesuada ligula, eu luctus felis ullamcorper a. Praesent massa massa, cursus non mauris in, finibus porta metus. Integer gravida et risus ac scelerisque. Mauris ut tellus efficitur nunc gravida pharetra. Phasellus vitae nisi vitae tellus mollis consequat tincidunt semper risus. Vivamus nec nulla vitae nunc tristique ornare.  Nulla facilisi. Phasellus nisl sem, imperdiet eget hendrerit elementum, semper quis justo. Mauris at purus hendrerit, molestie orci ut, maximus est. Praesent congue tincidunt sapien, vitae egestas neque auctor sed. Curabitur feugiat orci lorem, a fringilla leo fringilla malesuada. Praesent mattis ornare magna, id consectetur massa. Etiam consectetur lorem eu pellentesque sollicitudin. Proin dapibus leo eu justo.",
        indiv_promo_rec=3,
        senior_address="123 Main St, Anytown, USA",
    )


def build_validated_example_chiefeval() -> ChiefEval:
    return ChiefEval(
        id=1,
        name="DOE, JANE A",
        rate="CWTC",
        desig="1110",
        ssn="123-45-6789",
        group=DutyStatus.ACT,
        uic="12345",
        station="NAVPERSCOM",
        promotion_status=PromotionStatus.REGULAR,
        date_reported=date(2024, 5, 15),
        periodic=True,
        det_indiv=False,
        det_rs=False,
        special=False,
        period_start=date(2024, 6, 1),
        period_end=date(2024, 12, 31),
        not_observed=False,
        regular=True,
        concurrent=False,
        ops_cdr=False,
        physical_readiness="P",
        billet_subcategory=BilletSubcategory.BASIC,
        senior_name="SMITH, JOHN Q",
        senior_grade="CAPT",
        senior_desig="1110",
        senior_title="CO",
        senior_uic="12345",
        senior_ssn="987-65-4321",
        job="Leads command-level mission execution and mentoring for chief mess responsibilities.",
        duties_abbreviation="CMC",
        duties_description="Serves as command senior enlisted advisor across mission and readiness functions.",
        date_counseled=date(2024, 7, 1),
        counselor="SMITH, J",
        trait1=3,
        trait2=3,
        trait3=3,
        trait4=3,
        trait5=3,
        trait6=3,
        trait7=3,
        career_rec_1="",
        career_rec_2="",
        comments="Strong chief with sustained impact on readiness and team performance.",
        indiv_promo_rec=3,
        senior_address="123 Fleet St, Norfolk VA",
    )


def build_validated_example_eval() -> Eval:
    return Eval(
        id=1,
        name="SMITH, ALEX R",
        rate="YN1",
        desig="YN",
        ssn="111-22-3333",
        group=DutyStatus.ACT,
        uic="54321",
        station="NAVPERSCOM",
        promotion_status=PromotionStatus.REGULAR,
        date_reported=date(2024, 7, 1),
        periodic=True,
        det_indiv=False,
        special=False,
        prom_frock=False,
        period_start=date(2024, 7, 1),
        period_end=date(2024, 12, 31),
        not_observed=False,
        regular=True,
        concurrent=False,
        physical_readiness="P",
        billet_subcategory=BilletSubcategory.BASIC,
        senior_name="JOHNSON, C",
        senior_grade="LCDR",
        senior_desig="6410",
        senior_title="ADMIN O",
        senior_uic="54321",
        senior_ssn="999-88-7777",
        job="Led departmental admin transformation and improved processing quality across command workflows.",
        duties_abbreviation="ADMIN",
        duties_description="Managed personnel administration, training records, and readiness reporting across the department.",
        date_counseled=date(2024, 8, 1),
        counselor="JOHNSON, C",
        trait1=4,
        trait2=4,
        trait3=4,
        trait4=4,
        trait5=4,
        trait6=4,
        trait7=4,
        achievements="Delivered high-quality admin support and mentorship with measurable command impact.",
        career_rec_1="ASSIGN TO FLAG STA",
        career_rec_2="ADVANCE ASAP",
        comments="Strong performer with sustained leadership impact and outstanding mission support.",
        indiv_promo_rec=4,
        retain=RetentionRecommendation.RECOMMENDED.value,
        senior_address="456 Fleet Ave, Norfolk VA",
    )
